import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {
  Input,
  Button,
  FormControl,
  FormLabel,
  Stack,
  Grid, 
  GridItem
} from '@chakra-ui/react';
import { useState } from 'react';
import erc3525 from "public/erc3525_diagram.png"; 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [inputValue, setInputValue] = useState('');

  const [inputValue1, setInputValue1] = useState('');
  const [inputValue2, setInputValue2] = useState('');
  const [inputValue3, setInputValue3] = useState('');
  const [inputValue4, setInputValue4] = useState('');

  const handleInputChange1 = (event) => {
    setInputValue1(event.target.value);
  };
  
  const handleInputChange2 = (event) => {
    setInputValue2(event.target.value);
  };
  
  const handleInputChange3 = (event) => {
    setInputValue3(event.target.value);
  };
  
  const handleInputChange4 = (event) => {
    setInputValue4(event.target.value);
  };

  const handleButtonClick = () => {
    console.log('Button clicked with input value:', inputValue);
    // Do something with input value, such as sending to server
  };
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            
            <code className={styles.code}>ERC3525 Data Market Demo</code>
          </p>
          <div>
            {/* <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a> */}
          </div>
        </div>

      <div className={styles.center}>
          <div className={styles.rightPart}>
            <Grid templateColumns="repeat(2, 1fr)" gap={4} className={styles.dataInput}>
          <GridItem>
            <FormControl>
              <FormLabel>Enter Data Name:</FormLabel>
              <Input value={inputValue1} onChange={handleInputChange1} />
            </FormControl>
          </GridItem>
          <GridItem>
            <FormControl>
              <FormLabel>Enter Data Estimated Value:</FormLabel>
              <Input value={inputValue2} onChange={handleInputChange2} />
            </FormControl>
          </GridItem>
          <GridItem>
            <FormControl>
              <FormLabel>Enter Data Type:</FormLabel>
              <Input value={inputValue3} onChange={handleInputChange3} />
            </FormControl>
          </GridItem>
          <GridItem>
            <FormControl>
              <FormLabel>Tokenized Value Range:</FormLabel>
              <Input value={inputValue4} onChange={handleInputChange4} />
            </FormControl>
          </GridItem>
          <GridItem colSpan={2} >
            <Button className={styles.submitButton} onClick={handleButtonClick}>Submit</Button>
          </GridItem>
            </Grid>
          </div>
          <div className={styles.leftPart}>
          
            <div className={styles.displayData}>
            <div className={styles.gridContainer}>
              <Grid gap={12}>
                <div>Data Name: </div>
                <div>Data Value: </div>
                <div>Data Type: </div>
                <div>Data Range: </div>
                </Grid>
            </div>
            </div>
            <div className={styles.imageContainer}>
          <Image
                className = {styles.erc3525}
                src={erc3525}
                alt="erc3525"  
                width={100}
                height={100}
                priority
              />
              </div>
          </div>
        </div>

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
